spring:
  application:
    name: gestao-streaming
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/gestao_streaming}
    username: ${SPRING_DATASOURCE_USERNAME:gestao}
    password: ${SPRING_DATASOURCE_PASSWORD:gestao}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
    properties:
      hibernate:
        format_sql: true

tmdb:
  base-url: ${TMDB_BASE_URL:https://api.themoviedb.org/3}
  api-token: ${TMDB_API_TOKEN:eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJkM2UwYTkwOGRkMDVhMWNmNDQwZDQ1OTM2Y2FjYmY2NSIsIm5iZiI6MTc4MTk1NjM2Ny43OTAwMDAyLCJzdWIiOiI2YTM2N2YwZjc2MWFmOWMwYjFlNmZkNmIiLCJzY29wZXMiOlsiYXBpX3JlYWQiXSwidmVyc2lvbiI6MX0.w_huCVIHcg7YjMJmqvxwz9jSWQDrbZHaxmMNwvBOPfk}
  default-region: ${TMDB_DEFAULT_REGION:BR}
  default-language: ${TMDB_DEFAULT_LANGUAGE:pt-BR}
